"""The paper's tables, generated from the result files so no number is typed twice:
docs/research-results.md (E1-E3) and docs/scorecard.md (Tiers A-C) -> paper/tables/*.tex.

Run: python paper/tables.py   (standard library only)
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).parent / "tables"
SOURCES = {"research-results.md": ("E1", "E2", "E3"), "scorecard.md": ("Tier A", "Tier B", "Tier C")}


def _sections(text: str) -> dict[str, str]:
    return {part.split(":", 1)[0].strip(): part for part in text.split("\n## ")[1:]}


def _rows(section: str) -> list[list[str]]:
    lines = [ln for ln in section.splitlines() if ln.startswith("|")]
    return [[c.strip() for c in ln.strip("|").split("|")] for ln in lines if not set(ln) <= set("|-: ")]


def _tex(cell: str) -> str:
    cell = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", cell)
    cell = re.sub(r"`(.+?)`", r"\\texttt{\1}", cell)
    cell = cell.replace("%", r"\%").replace("$", r"\$").replace("&", r"\&").replace("_", r"\_").replace("#", r"\#")
    return re.sub(r'"(.+?)"', r"``\1''", cell)


def table(rows: list[list[str]]) -> str:
    head, *body = rows
    spec = "l" + "r" * (len(head) - 1)
    lines = [rf"\begin{{tabular}}{{{spec}}}", r"\toprule", " & ".join(_tex(c) for c in head) + r" \\", r"\midrule"]
    lines += [" & ".join(_tex(c) for c in r) + r" \\" for r in body]
    return "\n".join(lines + [r"\bottomrule", r"\end{tabular}", ""])


def main() -> None:
    OUT.mkdir(exist_ok=True)
    for name, wanted in SOURCES.items():
        path = ROOT / "docs" / name
        if not path.exists():
            continue
        sections = _sections(path.read_text(encoding="utf-8"))
        for key in wanted:
            if key in sections and (rows := _rows(sections[key])):
                target = OUT / (key.lower().replace(" ", "_") + ".tex")
                target.write_text(f"% Generated by paper/tables.py from docs/{name}: don't edit.\n" + table(rows),
                                  encoding="utf-8")
                print(f"-> {target.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
