"""The paper's tables, generated from the result files so no number is typed twice:
docs/research-results.md (E1-E4) and docs/scorecard.md (Tiers A-C) -> paper/tables/*.tex.

Run: python paper/tables.py   (standard library only)
"""

import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).parent / "tables"
CONSTANTS = {"FLIP_WEIGHT": "flipweight", "STOP_BELOW": "stopbelow", "QUICK_QUESTIONS": "quickquestions"}  # name in interview.py -> LaTeX macro
SOURCES = {"research-results.md": ("E1", "E2", "E3", "E4"), "scorecard.md": ("Tier A", "Tier B", "Tier C")}


def _sections(text: str) -> dict[str, str]:
    return {part.split(":", 1)[0].strip(): part for part in text.split("\n## ")[1:]}


def _tables(section: str) -> list[list[list[str]]]:
    """Each markdown table in the section (separated by other lines), as rows of cells."""
    tables, rows = [], []
    for ln in section.splitlines() + [""]:
        if ln.startswith("|"):
            if not set(ln) <= set("|-: "):
                rows.append([c.strip() for c in ln.strip("|").split("|")])
        elif rows:
            tables.append(rows)
            rows = []
    return tables


def _tex(cell: str) -> str:
    cell = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", cell)
    cell = re.sub(r"`(.+?)`", r"\\texttt{\1}", cell)
    cell = cell.replace("%", r"\%").replace("$", r"\$").replace("&", r"\&").replace("_", r"\_").replace("#", r"\#")
    return re.sub(r'"(.+?)"', r"``\1''", cell)


def table(rows: list[list[str]]) -> str:
    head, *body = rows
    spec = "l" + "r" * (len(head) - 1)
    lines = [rf"\begin{{tabular}}{{{spec}}}", r"\toprule", " & ".join(_tex(c) for c in head) + r" \\", r"\midrule"]
    lines += [" & ".join(_tex(c) for c in r) + r" \\" for r in body]
    return "\n".join(lines + [r"\bottomrule", r"\end{tabular}", ""])


def constants() -> str:
    """The interview's tuning (w and tau in the paper), read from where it's defined."""
    tree = ast.parse((ROOT / "engine" / "unclaimed_engine" / "interview.py").read_text(encoding="utf-8"))
    value = {t.id: ast.literal_eval(n.value) for n in tree.body if isinstance(n, ast.Assign)
             for t in n.targets if isinstance(t, ast.Name) and t.id in CONSTANTS}
    return "".join(rf"\newcommand{{\{cmd}}}{{{value[name]:,}}}" + "\n" for name, cmd in CONSTANTS.items())


def main() -> None:
    OUT.mkdir(exist_ok=True)
    (OUT / "constants.tex").write_text("% Generated by paper/tables.py from engine/unclaimed_engine/interview.py: don't edit.\n"
                                       + constants(), encoding="utf-8")
    for name, wanted in SOURCES.items():
        path = ROOT / "docs" / name
        if not path.exists():
            continue
        sections = _sections(path.read_text(encoding="utf-8"))
        for key in wanted:
            for i, rows in enumerate(_tables(sections.get(key, ""))):
                stem = key.lower().replace(" ", "_") + (f"_{i + 1}" if i else "")  # e4.tex, e4_2.tex, ...
                target = OUT / f"{stem}.tex"
                target.write_text(f"% Generated by paper/tables.py from docs/{name}: don't edit.\n" + table(rows),
                                  encoding="utf-8")
                print(f"-> {target.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
